# Minimal configuration for ZE15-CO sensor
esphome:
  name: co-sensor
  platform: ESP32
  board: esp32dev

# Change these to your network
wifi:
  ssid: "YourWiFi"
  password: "YourPassword"

api:
ota:

# External component from GitHub
external_components:
  - source: github://Bjk8kds/esphome-winsen-co-sensor
    components: [ ze15_co ]

# UART pins - adjust to your wiring
uart:
  rx_pin: GPIO16  # Connect to sensor TX
  tx_pin: GPIO17  # Connect to sensor RX (optional for Initiative mode)
  baud_rate: 9600

# CO sensor - minimal config (Initiative mode)
sensor:
  - platform: ze15_co
    co:
      name: "CO Level"
# Note: This uses Initiative mode (real-time data every second)

# To use Q&A mode, add update_interval:
  sensor:
    - platform: ze15_co
      update_interval: 60s  # Any value ≥ 5s
      co:
        name: "CO Level"
